services:
  maven-testing:
    command: sleep 600000
    image: maven:3-alpine
    volumes:
    - source: ./
      target: /sqaaas-build
      type: bind
    working_dir: /sqaaas-build
version: '3.7'
