services:
  maven-testing:
    command: sleep 600000
    hostname: maven-testing
    image: maven:3-alpine
    volumes:
    - source: ./
      target: /maven-project
      type: bind
    working_dir: /maven-project
version: '3.7'
